workspace 'TeamTalk'
platform:ios, '8.0'

target 'TeamTalk' do
    pod 'FMDB'
    pod 'SDWebImage'
    pod 'AFNetworking', '~> 2.3.0'
    pod 'DACircularProgress'
    pod 'MBProgressHUD'
    pod 'PSTCollectionView'
    pod 'HPGrowingTextView'
    pod 'ProtocolBuffers'
    pod 'leveldb-library'
    pod 'SCLAlertView-Objective-C'
    pod 'MWPhotoBrowser', '~> 1.4.1'
end
